# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: add msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'

    - name: build
      run: msbuild FTPLibrary.sln /property:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg -verbosity:diagnostic
    
    - name: pack
      run: |
        nuget pack src/FTPLibrary.nuspec -symbols -symbolpackageformat snupkg
        nuget pack src/FTPLibrary.csproj -prop configuration=release -verbosity detailed -outputdirectory ${{ github.workspace }}\package -symbols -symbolpackageformat snupkg

    - uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: ${{ github.workspace }}\package
    
    - name: publish package
      run: |
        nuget push ${{ github.workspace }}\package\*.nupkg -source https://api.nuget.org/v3/index.json -skipduplicate -nosymbols -verbosity detalied -apikey ${{ secrets.NUGET_API_KEY }}
